name: Checkmarx AST Scan
on:
  pull_request:
    types: [opened, reopened, synchronize] #Types specify which pull request events will trigger the workflow. For more events refer Github Actions documentation.
    branches:
      - master
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action versionn
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: cx_ps_mariana_teixeira
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --sast-preset-name "ASA Premium"
                              --tags "pr:${{ github.ref }}"
                              --file-filter '!*README.md,!*app-hello-world*.js'
                              --threshold "sast-high=10; sast-medium=20; sca-high=10; containers-high=5"
    
